//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ammunition
    {
        public int AmmunitionID { get; set; }
        public string Name { get; set; }
        public int Damage { get; set; }
        public int Penetration { get; set; }
        public int ArmourDamage { get; set; }
        public int Accuracy { get; set; }
        public int Recoil { get; set; }
        public decimal FragmentationChance { get; set; }
        public decimal RicochetChance { get; set; }
        public int Speed { get; set; }
        public int CaliberID { get; set; }
    
        public virtual Caliber Caliber { get; set; }
    }
}
