//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loadout
    {
        public int LoadoutID { get; set; }
        public string Name { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EarpieceID { get; set; }
        public Nullable<int> HeadwearID { get; set; }
        public Nullable<int> BodyArmourID { get; set; }
        public Nullable<int> PrimaryWeaponID { get; set; }
        public Nullable<int> SecondaryWeaponID { get; set; }
        public Nullable<int> HolsterWeaponID { get; set; }
        public Nullable<int> RigID { get; set; }
        public Nullable<int> BackpackID { get; set; }
    
        public virtual Gear Gear { get; set; }
        public virtual Gear Gear1 { get; set; }
        public virtual Gear Gear2 { get; set; }
        public virtual Gear Gear3 { get; set; }
        public virtual Gear Gear4 { get; set; }
        public virtual User User { get; set; }
        public virtual Weapon Weapon { get; set; }
        public virtual Weapon Weapon1 { get; set; }
        public virtual Weapon Weapon2 { get; set; }
    }
}
