//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Weapon()
        {
            this.Loadouts = new HashSet<Loadout>();
            this.Loadouts1 = new HashSet<Loadout>();
            this.Loadouts2 = new HashSet<Loadout>();
        }
    
        public int WeaponID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Slot { get; set; }
        public decimal Weight { get; set; }
        public int VerticalRecoil { get; set; }
        public int HorizontalRecoil { get; set; }
        public int Range { get; set; }
        public int Ergonomics { get; set; }
        public int FireRate { get; set; }
        public bool Single { get; set; }
        public bool Burst { get; set; }
        public bool Auto { get; set; }
        public int CaliberID { get; set; }
    
        public virtual Caliber Caliber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loadout> Loadouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loadout> Loadouts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loadout> Loadouts2 { get; set; }
    }
}
